### ISSUE TITLE
responsive web design

### ISSUE THREAD

**Issue by michalbe** [klasiik/html-template-02#3]
Strona powinna dostosowywać się do szerokości ekranu. Na małych monitorach wyglada tak:
![screen-2015 11 14 22 21 28](https://cloud.githubusercontent.com/assets/347657/11165894/21832fb4-8b1e-11e5-8b4b-6e20a06d4eae.png)

Na dużych tak:
![screen-2015 11 14 22 21 16](https://cloud.githubusercontent.com/assets/347657/11165895/21aff56c-8b1e-11e5-8e3f-b90baa2b6412.png)

Wszystkie elementy powinny się same dostosowywać do rozmiarów ekranu.

Rozmiary powinny być zrobione na procentach lub powinny mieć krokowe wymiary dla najpopularniejszych rozdzielczości zrobione przy uzyciu `media queries`. Wygooglaj:
- [Responsive Web Design](https://www.google.pl/search?q=responsive+web+design)
- [Media Queries](https://www.google.pl/search?q=css+media+queries)

Pomocne do testowania tego będą też responsywne narzędzia w przeglądarkach:
- [Firefox](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_View)
- [Chrome](http://blog.chromium.org/2014/09/responsive-web-design-with-devtools.html)

**Comment by klasiik** [comment]
Dodane RWD
