### ISSUE TITLE
hover na obrazkach jest okropny

### ISSUE THREAD

**Issue by michalbe** [klasiik/html-template-02#5]
Zrób tak żeby obrazki były w divach o rozmiarach tych obrazków, ale żeby te divy miały ustawione `overflow: hidden` (co znaczy że jak cos jest wieksze niż ten div to sie nie wyswietla, zostaje wykadrowane). A na hover daj obrazkom `transform: scale(1.2)`, do tego ustaw im `transition`  na ten transform jakiś krotki, powiedzmy 0.3s. Prosty efekt a mega kozacki (na pewno lepszy niz chujowe ramki).

**Comment by klasiik** [comment]
Hover poprawiony
