### ISSUE TITLE
dynamiczne generowanie miniaturek.

### ISSUE THREAD

**Issue by michalbe** [klasiik/html-template-02#6]
Zrob sobi plik jsowy a w nim arraya z danymi, np, tak:

``` javascript
var newUsers = [
  'ADA',
  'ADALBERT',
  'ADAM',
  'ADELA' ,
  'ADRIAN',
  'ADRIANA',
  'ADRIANNA',
  'AGATA',
  'ALEKSANDER'
];
```

Potem wypierdol te miniaturki nowych ludzi i niech generuje je JS (przerabialismy to juz - `document.createElement` itp.) i niech oprocz pobrazkow dodaje te podpisy ktore masz w arrayu, w ten sposób ze jak sobie zmienie `ADAM` na `CWEL` to wyswietli sie na stronie glownej nowy user o imieniu cwel.

**Comment by klasiik** [comment]
generowanie dymaniczne dodane
