### ISSUE TITLE
[Trudniejsze] zmiana jezyka

### ISSUE THREAD

**Issue by michalbe** [klasiik/html-template-02#7]
Na gorze masz ikonki z jezykami. Podepij pod nie akcje zmiany jezyka.

Podpowiedzi:
- Zrob sobie obiekty ktore beda mialy teksty w roznych jezykach, cos takiego:

``` javascript
var polish = {
  login: 'Logowanie',
  password: 'Hasło',
  // .... itp.
};

var english ={
  login: 'Login',
  password: 'Password',
  // .... itp.
};

var german ={
  login: 'Login',
  password: 'Passwort',
  // .... itp.
};
```
- Potem dajesz kazdemu elementowi ktory ma tekst (kazdemu spanowi, divovi, itp) np. atrubut `data-language` o wartosci klucza w obiekcie jezykowym ktory stworzyles wczesniej:

``` javascript
<label for="password" data-language="password">Hasło:</label>
<label for="password" data-language="login">Login:</label>
```
- Po kliknieciu na przycisk zmiany języka powinieneś znaleźć wszystkie elementy które mają atrybut `data-language` (pomoże Ci w tym `querySelectorAll`) i zmienić im `innerHTML` albo `textContent` (poczytaj jaka jest roznica) na taki jak jest w Twoim obiekcie jezykowym dla danego jezyka.

**Comment by klasiik** [comment]
Skrypt zmieniający język dodany

**Comment by klasiik** [comment]
Skrypt zmieniający język dodany
